In [1]:
import pandas as pd

# importing database
df = pd.read_csv(r"./clicks_sample.csv")

df.head()

,user_id,session_id,session_start,session_size,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,0,1506825423271737,1506825423000,2,157541,1506826828020,4,3,20,1,20,2
1,0,1506825423271737,1506825423000,2,68866,1506826858020,4,3,20,1,20,2
2,1,1506825426267738,1506825426000,2,235840,1506827017951,4,1,17,1,16,2
3,1,1506825426267738,1506825426000,2,96663,1506827047951,4,1,17,1,16,2
4,2,1506825435299739,1506825435000,2,119592,1506827090575,4,1,17,1,24,2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1883 entries, 0 to 1882
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              1883 non-null   int64
 1   session_id           1883 non-null   int64
 2   session_start        1883 non-null   int64
 3   session_size         1883 non-null   int64
 4   click_article_id     1883 non-null   int64
 5   click_timestamp      1883 non-null   int64
 6   click_environment    1883 non-null   int64
 7   click_deviceGroup    1883 non-null   int64
 8   click_os             1883 non-null   int64
 9   click_country        1883 non-null   int64
 10  click_region         1883 non-null   int64
 11  click_referrer_type  1883 non-null   int64
dtypes: int64(12)
memory usage: 176.7 KB

In [3]:
df.describe()

,user_id,session_id,session_start,session_size,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
count,1883.000000,1.883000e+03,1.883000e+03,1883.000000,1883.000000,1.883000e+03,1883.000000,1883.000000,1883.000000,1883.000000,1883.000000,1883.000000
mean,355.893787,1.506828e+15,1.506828e+12,3.459904,176717.848646,1.506830e+12,3.917153,2.305895,12.113648,1.491768,18.774827,1.764206
std,206.162865,8.679628e+08,8.679468e+05,3.037467,82324.177259,1.064938e+07,0.410461,1.062301,7.825735,2.007772,7.083400,1.225679
min,0.000000,1.506825e+15,1.506825e+12,2.000000,2137.000000,1.506827e+12,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000
25%,181.500000,1.506827e+15,1.506827e+12,2.000000,108854.000000,1.506828e+12,4.000000,1.000000,2.000000,1.000000,13.000000,1.000000
50%,353.000000,1.506828e+15,1.506828e+12,3.000000,157541.000000,1.506828e+12,4.000000,3.000000,17.000000,1.000000,21.000000,1.000000
75%,537.000000,1.506828e+15,1.506828e+12,4.000000,236697.500000,1.506829e+12,4.000000,3.000000,19.000000,1.000000,25.000000,2.000000
max,706.000000,1.506829e+15,1.506829e+12,24.000000,363291.000000,1.506998e+12,4.000000,4.000000,20.000000,11.000000,28.000000,7.000000

In [4]:
df.corr()

,user_id,session_id,session_start,session_size,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
user_id,1.000000,0.990634,0.990635,0.071280,-0.098768,-0.023409,0.006608,0.068448,0.048096,0.080579,-0.017209,-0.030667
session_id,0.990634,1.000000,1.000000,0.071308,-0.098094,-0.033425,-0.002511,0.077725,0.038449,0.084023,-0.017713,-0.022870
session_start,0.990635,1.000000,1.000000,0.071313,-0.098094,-0.033413,-0.002507,0.077727,0.038454,0.084035,-0.017701,-0.022879
session_size,0.071280,0.071308,0.071313,1.000000,0.119985,0.085989,0.042510,0.077906,0.137911,-0.001731,0.056282,-0.176948
click_article_id,-0.098768,-0.098094,-0.098094,0.119985,1.000000,-0.003986,0.025627,0.010898,-0.017495,-0.035355,0.131181,-0.004447
click_timestamp,-0.023409,-0.033425,-0.033413,0.085989,-0.003986,1.000000,0.032341,-0.149662,0.089530,-0.018454,-0.074167,-0.006030
click_environment,0.006608,-0.002511,-0.002507,0.042510,0.025627,0.032341,1.000000,-0.197755,-0.039745,-0.002762,0.050417,-0.036737
click_deviceGroup,0.068448,0.077725,0.077727,0.077906,0.010898,-0.149662,-0.197755,1.000000,-0.389212,0.035062,0.046796,-0.027009
click_os,0.048096,0.038449,0.038454,0.137911,-0.017495,0.089530,-0.039745,-0.389212,1.000000,0.033539,0.011044,-0.060633
click_country,0.080579,0.084023,0.084035,-0.001731,-0.035355,-0.018454,-0.002762,0.035062,0.033539,1.000000,0.319161,0.008495
click_region,-0.017209,-0.017713,-0.017701,0.056282,0.131181,-0.074167,0.050417,0.046796,0.011044,0.319161,1.000000,-0.037576
click_referrer_type,-0.030667,-0.022870,-0.022879,-0.176948,-0.004447,-0.006030,-0.036737,-0.027009,-0.060633,0.008495,-0.037576,1.000000

In [5]:
df.isna().sum()

user_id                0
session_id             0
session_start          0
session_size           0
click_article_id       0
click_timestamp        0
click_environment      0
click_deviceGroup      0
click_os               0
click_country          0
click_region           0
click_referrer_type    0
dtype: int64

In [7]:
import numpy as np
from csv import writer 

# Path to click_sample dataset 
m_path = r"./clicks_sample.csv"

# Asked columns of the data set
clickEnvironment_df = pd.read_csv(m_path, usecols=['click_environment']) 
deviceGroup_df = pd.read_csv(m_path, usecols=['click_deviceGroup'])
operatingSystem_df = pd.read_csv(m_path, usecols=['click_os'])

# Empty array to append later
m_arr =  np.array([])
m_arr2 =  np.array([])
m_arr3 =  np.array([])

# Convert dataframes to numpy for calculating
temp = clickEnvironment_df.to_numpy()
temp2 = deviceGroup_df.to_numpy()
temp3 = operatingSystem_df.to_numpy()

# imaginary time interval for taking most average values of columns
clickDf_step = 30

def distribution_of_click(file_name, list_of_elem, list_of_elem_1,list_of_elem_2):
    evironment = ""
    device = ""
    os = ""

# Etiquete for the values
# They will be added on csv file
    if list_of_elem > 3:
        environment = "Web"
    elif list_of_elem > 2: 
        environment = "AMP"
    elif list_of_elem > 1:
        environment = "Mobile App"
    elif list_of_elem > 0:
        environment = "FaceBook Instant Article"
    else:
        environment = "Null Data"
        
    if list_of_elem_1 > 4:
        device = "Desktop"
    elif list_of_elem_1 > 3:
        device = "Mobile"
    elif list_of_elem_1 > 2:
        device = "Empty"
    elif list_of_elem_1 > 1:
        device = "TV"
    elif list_of_elem_1 > 0:
        device = "Tablet"
    else:
        device = "Null Data"
        
        
    if list_of_elem_2 > 22:
        os = "Solaris"
    elif list_of_elem_2 > 21:
        os = "Gentoo"
    elif list_of_elem_2 > 20:
        os = "webOS"
    elif list_of_elem_2 > 19:
        os = "Chromecast"
    elif list_of_elem_2 > 18:
        os = "Brew MP"
    elif list_of_elem_2 > 17:
        os = "Android"
    elif list_of_elem_2 > 16:
        os = "Firefox OS"
    elif list_of_elem_2 > 15:
        os = "BlackBerry OS"
    elif list_of_elem_2 > 14:
        os = "Symbian OS"
    elif list_of_elem_2 > 13:
        os = "Debian"
    elif list_of_elem_2 > 12:
        os = "Chrome OS"
    elif list_of_elem_2 > 11:
        os = "tvOS"
    elif list_of_elem_2 > 10:
        os = "ATV OS X"
    elif list_of_elem_2 > 9:
        os = "FireHbbTV"
    elif list_of_elem_2 > 8:
        os = "Samsung"
    elif list_of_elem_2 > 7:
        os = "Mac OS X"
    elif list_of_elem_2 > 6:
        os = "Windows"
    elif list_of_elem_2 > 5:
        os = "Windows Mobile"
    elif list_of_elem_2 > 4: 
        os = "Windows Phone"
    elif list_of_elem_2 > 3:
        os = "Android"
    elif list_of_elem_2 > 2:
        os = "iOS"
    elif list_of_elem_2 > 1:
        os = "Other"
    else:
        os = "Null Data"
        
        
    with open(file_name, 'a+', newline='') as write_obj:
        # Create a writer object from csv module
        csv_writer = writer(write_obj)
        # Add contents of list as last row in the csv file
        csv_writer.writerow([list_of_elem, environment, list_of_elem_1, device, list_of_elem_2, os])
        


    
    
# Take average values for adding to the csv file        
for i in range(1, len(temp), clickDf_step):
    arr = np.append(m_arr,np.array([np.average(temp[i:i + clickDf_step])]))
    arr2 = np.append(m_arr2,np.array([np.average(temp2[i:i + clickDf_step])]))
    arr3 = np.append(m_arr3,np.array([np.average(temp3[i:i + clickDf_step])]))
    
    distribution_of_click('event.csv',arr,arr2,arr3)